### ISSUE TITLE
temporarily move back to testing

### ISSUE THREAD

**Issue by carlwgeorge** [iusrepo/php72u#1]
We will be temporarily moving php72u packages back to the testing repos.  We discovered that php72u being present in the stable repos is causing issues installing php71u-pecl-\* packages.

```
yum install php71u-pecl-redis
```
```
Error: php72u-common conflicts with php71u-common-7.1.13-1.ius.centos7.x86_64
```

To work around this temporarily you can exclude php72u packages from the dependency resolution.

```
yum install php71u-pecl-redis --exclude php72u\*
```

The php72u packages we have built so far will still be available in the testing repos during this period.

```
yum --enablerepo ius-testing install php72u-pecl-redis
```

Note: this issue is not specific to php\*-pecl-redis, that's just what I used for my examples.

This is due to the post(un)install scriptlet requirement on pecl, which is a component of pear.  In php70u and earlier, we shipped specific php\*u-pear packages for every stack.  In php71u, we decided to try a new approach and [created a common pear1u package][pear1u] to be shared for all future PHP stacks.  This worked as expected until php72u moved to the stable repos.  Now yum is showing it's age as it's dependency resolution is not capable of calculating the correct transaction and attempts to pull in a mix of php71u and php72u packages.  We didn't initially notice this during development because we build packages with mock on Fedora, which uses dnf to set up the build root.  Once all php71u-pecl-\* packages have been updated to address this, we'll republish php72u packages to the stable repos again.

[pear1u]: https://github.com/iuscommunity/wishlist/issues/104#issuecomment-266562238

**Comment by crankedguy** [comment]
Can you tell about how long this will take approximately?

Thanks

**Comment by carlwgeorge** [comment]
Nope, it will take as long as it takes.  If you need php72u packages now just get them from the testing repo.

**Comment by b-harper** [comment]
I wanted to give a progress update on this issue.  @carlwgeorge, has made the needed changes to all of the php71u-pecl-* packages and they are currently in the testing repositories.  Based on our testing, we are no longer seeing the dependency issue.    We would like to keep the packages in the testing repositories for a few days.  If no addition issues are discovered or reported, we plan on pushing all of the php71u-pecl-* and php72u* packages to the stables repositories during the automation run on Monday night.

**Comment by carlwgeorge** [comment]
Everything is on track for php72u and related packages to move to back to the stable repos during tonight's automation.
