### ISSUE TITLE
PHP 7.2.15

### ISSUE THREAD

**Issue by ralfbecker** [iusrepo/php72u#10]
I want to politly inquire about the missing PHP update, it has been released a while ago.

Ralf

**Comment by ralfbecker** [comment]
Thanks :)

**Comment by carlwgeorge** [comment]
Build is in progress, it will get published to the testing repo during tonight's automation.

**Comment by carlwgeorge** [comment]
Sorry this is taking a little bit longer, I've had some sync issues with Red Hat for my mock build roots.  I'll update this again once I get it sorted out.

**Comment by carlwgeorge** [comment]
[php72u-7.2.15-1](https://github.com/iuscommunity-pkg/php72u/releases/tag/7.2.15-1) is live in the testing repos now.
