### ISSUE TITLE
7.2.18 missing from repo

### ISSUE THREAD

**Issue by ralfbecker** [iusrepo/php72u#11]
While 7.2.18 is in released state since 22 days in this repo, it has NOT appeared in the stable repository: 
https://dl.iuscommunity.org/pub/ius/stable/Redhat/7/x86_64/

Any specific reason, or just an oversight?

Ralf

**Comment by carlwgeorge** [comment]
Nice catch.  It was just an oversight.  We have been focused on our [transition from the mirror network to a CDN](https://github.com/iusrepo/infrastructure/issues/14).  I had already promoted 7.2.18 to stable on the CDN.  Now I've done the same on the legacy file server.  It should sync out to the mirror network in the next day or two.  Thanks for letting me know!
