### ISSUE TITLE
php72u-fpm error.log is not rotated due to missing PID file

### ISSUE THREAD

**Issue by aderixon** [iusrepo/php72u#17]
The file `/var/log/php-fpm/error.log` is not rotated by the `/etc/logrotate.d/php-fpm` configuration because the file `/run/php-fpm/php-fpm.pid` is missing so logrotate can't signal the daemon. This is because the pid setting is undefined in `/etc/php-fpm.conf`:

```
[global]
; Pid file
; Default Value: none
;pid = /run/php-fpm/php-fpm.pid
```

This may become an issue when enabling `catch_workers_output` to log debug output.

**Comment by carlwgeorge** [comment]
Thanks for reporting this issue.  It looks like Fedora has addressed this by uncommenting the pid setting you referenced.

https://src.fedoraproject.org/rpms/php/c/363c6c25e9b1ce06923497dba24c3693661ba39c

We should make the same change to php71u and php72u.  Would you like to send pull requests for this change?

**Comment by carlwgeorge** [comment]
Thanks @zigman79 for the pull request to fix php72u.  That update (7.2.23-2) has been published to the testing repo.
