### ISSUE TITLE
php72u-fpm - problem with logrotate and ownership on /var/log/php-fpm 

### ISSUE THREAD

**Issue by jamieburchell** [iusrepo/php72u#2]
Not sure if this should be reported here or upstream, but I've run in to the above error installing php72u-fpm from the IUS repo:

/etc/cron.daily/logrotate:

error: skipping "/var/log/php-fpm/error.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.

Indeed the log directory is group writable:

`drwxrwx---. 2 php-fpm php-fpm      23 Apr 24 15:05 php-fpm`

I found a similar issue with a past package:

https://github.com/iuscommunity-pkg/php70u/issues/8

**Comment by carlwgeorge** [comment]
This is absolutely the right place @jamieburchell, thanks for reporting the problem.  As you found we addressed this already in previous packages, but it was missed while creating php72u.  I'll take care of it.

**Comment by jamieburchell** [comment]
Great! Thank you.

**Comment by carlwgeorge** [comment]
Fixed in [php72u-7.2.5-2](https://github.com/iuscommunity-pkg/php72u/releases/tag/7.2.5-2), and will move to the testing repos during tonight's automation.
