### ISSUE TITLE
Update to 7.2.27

### ISSUE THREAD

**Issue by djdevin** [iusrepo/php72u#21]
PHP 7.2.27 Release Announcement

The PHP development team announces the immediate availability of PHP 7.2.27. This is a security release.

All PHP 7.2 users are encouraged to upgrade to this version.

https://www.php.net/releases/7_2_27.php

**Comment by Vormillion** [comment]
When we can expect 7.2.27 to be available?

**Comment by carlwgeorge** [comment]
Thanks for the pull request @djdevin.  This update has been built and published to the testing repos.  I'll promote it to the main repos in a week or so to give people a chance to test it.

**Comment by carlwgeorge** [comment]
php72u-7.2.27-1 has been pushed to the main repos.
