### ISSUE TITLE
php72u seems to need some newer versions of libraries

### ISSUE THREAD

**Issue by rainerduffner** [iusrepo/php72u#25]
--> Running transaction check
---> Package php72u-mbstring.x86_64 0:7.2.31-2.el7.ius will be an update
--> Processing Dependency: libonig.so.5()(64bit) for package: php72u-mbstring-7.2.31-2.el7.ius.x86_64
---> Package samba-libs.x86_64 0:4.10.4-11.el7_8 will be installed
--> Processing Dependency: libpytalloc-util.so.2(PYTALLOC_UTIL_2.1.9)(64bit) for package: samba-libs-4.10.4-11.el7_8.x86_64
--> Processing Dependency: libpytalloc-util.so.2(PYTALLOC_UTIL_2.1.6)(64bit) for package: samba-libs-4.10.4-11.el7_8.x86_64
--> Processing Dependency: libpytalloc-util.so.2(PYTALLOC_UTIL_2.0.6)(64bit) for package: samba-libs-4.10.4-11.el7_8.x86_64
--> Processing Dependency: libpytalloc-util.so.2()(64bit) for package: samba-libs-4.10.4-11.el7_8.x86_64
--> Processing Dependency: libpyldb-util.so.1()(64bit) for package: samba-libs-4.10.4-11.el7_8.x86_64
--> Running transaction check
---> Package php72u-mbstring.x86_64 0:7.2.31-2.el7.ius will be an update
--> Processing Dependency: libonig.so.5()(64bit) for package: php72u-mbstring-7.2.31-2.el7.ius.x86_64
---> Package pyldb.x86_64 0:1.5.4-1.el7 will be installed
--> Processing Dependency: python-tdb(x86-64) >= 1.3.18 for package: pyldb-1.5.4-1.el7.x86_64
---> Package pytalloc.x86_64 0:2.1.16-1.el7 will be installed
--> Running transaction check
---> Package php72u-mbstring.x86_64 0:7.2.31-2.el7.ius will be an update
--> Processing Dependency: libonig.so.5()(64bit) for package: php72u-mbstring-7.2.31-2.el7.ius.x86_64
---> Package python-tdb.x86_64 0:1.3.18-1.el7 will be installed
--> Finished Dependency Resolution
Error: Package: php72u-mbstring-7.2.31-2.el7.ius.x86_64 (ew-ius7)
           Requires: libonig.so.5()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

There's no mention anywhere I could find where to get these.

**Comment by carlwgeorge** [comment]
Following the [instructions on the website](https://ius.io/setup), installing php72u-mbstring works as expected.  `libonig.so.5()(64bit)` is provided by oniguruma from EPEL.  This was [rebased recently](https://lists.fedoraproject.org/archives/list/epel-devel@lists.fedoraproject.org/thread/CNSWLDLHTWAEA6NKVI6YO3KKFP4Z2GY5/).  I don't know what `ew-ius7` is, so it looks like you're doing something custom.  My guess would be perhaps a local mirror of IUS and EPEL, in which case you need to sync those again to get the latest packages.
