### ISSUE TITLE
php72u packages no longer available?

### ISSUE THREAD

**Issue by ghost** [iusrepo/php72u#28]
I'm trying to install php72u under CentOS 7 but yum can't find any packages.

I looked at the repo and can't see any php72u packages, was php72u removed completely?

I've been looking under: https://repo.ius.io/7/x86_64/packages/p/

Thank you.

**Comment by ghost** [comment]
Apparently php72u has moved to the archives repo.

Maybe someone could update the[ FAQ section](https://ius.io/faq) to not mention php72u or at least mention that its in another repo?

Thank you.

**Comment by carlwgeorge** [comment]
When packages are retired we announce it with issues in https://github.com/iusrepo/announce.  I encourage all users of IUS subscribe to that repository.  php72u retirement was announced back in January in https://github.com/iusrepo/announce/issues/25.

> Maybe someone could update the FAQ section to not mention php72u or at least mention that its in another repo?

That someone can be you via a pull request to https://github.com/iusrepo/iusrepo.github.io.
