### ISSUE TITLE
Require packages libargon2-devel and libedit-devel for building embedded php applications

### ISSUE THREAD

**Issue by Chaz6** [iusrepo/php72u#3]
Right now if one wants to build an embedded php application, one must manually install `libedit-devel` and `libargon2-devel`. I would suggest one of the following alternatives:-

* Require the packages as part of php72u-devel
* Create a new target called php72u-embedded-devel

**Comment by carlwgeorge** [comment]
Adding those as requires for php72u-devel makes the most sense to me, but I would prefer to stay in line with the Fedora spec file.  Can you submit this as a bug for Fedora's php package?  Once implemented there I'll change the IUS spec file to follow suit.

https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&component=php

**Comment by carlwgeorge** [comment]
@Chaz6 Did you ever get around to reporting this to Fedora?

**Comment by Chaz6** [comment]
No I have not yet.

**Comment by carlwgeorge** [comment]
I'll reopen this if Fedora makes the change.
