### ISSUE TITLE
php72u-gd compile options (add webP Support)

### ISSUE THREAD

**Issue by futureweb** [iusrepo/php72u#4]
### What new package/feature do you want?

php72u-gd should be compiled with "--with-webp-dir=libwebp Directory" option.

### Why?

It's needed to create webP Images with PHP (http://php.net/manual/de/function.imagewebp.php)

### Testing

I agree to test the new package to ensure that it works as expected.  Once I am
satisfied with the results of my testing I will comment on this issue with the
word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
Thanks for pointing that out @futureweb.  It looks like we already do this with php71u, so I'll work on adding the flag to php72u.

**Comment by carlwgeorge** [comment]
Fixed in [php72u-7.2.7-2](https://github.com/iuscommunity-pkg/php72u/releases/tag/7.2.7-2).

**Comment by futureweb** [comment]
tested on our Dev-Server ... seems to work as expected! ;-)

**Comment by carlwgeorge** [comment]
Thanks for the confirmation, I'll queue it up for the stable repos.
